@startuml
title Battleship Sequence Diagram
actor Player1 #red
actor Player2 #green

participant GameApp
participant SocketServer




Player1->GameApp: Sets up the grid and click start game
GameApp->SocketServer: request to create a room
SocketServer->GameApp: Sends the room Id and playId(socketId)
GameApp-> Player1: gets the room Id link
Player1 -> Player2 : Share the room Id link
Player2 -> GameApp : Enter the room link and sets the grid and click start
GameApp->SocketServer: Request to join room with room Id and start the Game
SocketServer -> GameApp : Generate the player2 Id(socketId). And broadcast currentTurn to first player Id
GameApp -> Player1 : FireEnabled set true for Player 2 grid
Player1 -> GameApp : Player1 fires a click
GameApp -> SocketServer: socket.to(roomId).emit('fire', { rowIndex, columnIndex })
SocketServer -> GameApp: socket.on('fire') to check if cell is hit or miss
@enduml